/**
 * Committed contract for each server profile's externally visible tool surface.
 * Keep this explicit: deriving expectations from the registration code would let a
 * wiring mistake change both production and the test oracle at the same time.
 */
export const READ_ONLY_TOOL_NAMES = [
  'balancer_get_security_module_weights',
  'balancer_get_security_modules',
  'balancer_get_validator_status',
  'check_opt_in_l1',
  'check_opt_in_vault',
  'deployment_heartbeat',
  'discover_network',
  'health_check',
  'kite_info',
  'kite_info_delegator',
  'kite_info_validator',
  'l1_registry_get_all',
  'lst_wrapper_get_balance',
  'lst_wrapper_info',
  'lst_wrapper_max_deposit',
  'lst_wrapper_paused',
  'lst_wrapper_preview_deposit',
  'lst_wrapper_preview_redeem',
  'middleware_account_info',
  'middleware_epoch_rewards_report',
  'middleware_epoch_status',
  'middleware_get_active_nodes',
  'middleware_get_all_operators',
  'middleware_get_current_epoch',
  'middleware_get_linked_addresses',
  'middleware_get_node_logs',
  'middleware_get_operator_available_stake',
  'middleware_get_operator_locked_stake',
  'middleware_get_operator_stake',
  'middleware_get_operator_used_stake_per_epoch',
  'middleware_get_validator_balances',
  'middleware_info',
  'middleware_network_overview',
  'middleware_operator_dashboard',
  'middleware_stake_matrix',
  'middleware_uptime_report',
  'operator_registry_get_all',
  'rewards_epoch_diagnosis',
  'rewards_get_curator_shares',
  'rewards_get_distribution_batch',
  'rewards_get_epoch_rewards',
  'rewards_get_epoch_status',
  'rewards_get_events',
  'rewards_get_fees_config',
  'rewards_get_last_claimed',
  'rewards_get_min_uptime',
  'rewards_get_operator_shares',
  'rewards_get_vault_shares',
  'staking_vault_delegators_info',
  'staking_vault_epoch_info',
  'staking_vault_fees_info',
  'staking_vault_full_info',
  'staking_vault_info',
  'staking_vault_operators_info',
  'staking_vault_validators_info',
  'staking_vault_withdrawals_info',
  'uptime_get_validation_uptime_message',
  'vault_get_active_balance',
  'vault_get_active_stake',
  'vault_get_active_stake_at_epoch',
  'vault_get_balance',
  'vault_get_deposit_limit',
  'vault_get_total_supply',
  'vault_get_total_supply_at_epoch',
  'vault_get_withdrawals',
  'vault_helper_get_claimable_reward',
  'vault_helper_get_latest_distributed_rewards',
  'vault_helper_get_pending_withdraws',
  'vault_helper_info',
] as const;

export const FULL_WRITE_TOOL_NAMES = [
  'middleware_register_operator',
  'middleware_add_node',
  'middleware_init_stake_update',
  'middleware_weight_sync',
  'vault_deposit',
  'vault_withdraw',
  'vault_claim',
  'operator_registry_register',
  'l1_registry_register',
  'opt_in_l1',
  'opt_out_l1',
  'opt_in_vault',
  'opt_out_vault',
  'rewards_distribute',
  'rewards_claim',
  'kite_update_staking_config',
  'kite_initiate_validator_registration',
  'kite_complete_validator_registration',
  'kite_initiate_validator_removal',
  'kite_complete_validator_removal',
  'kite_initiate_delegator_registration',
  'kite_complete_delegator_registration',
  'kite_initiate_delegator_removal',
  'kite_complete_delegator_removal',
  'staking_vault_deposit',
  'staking_vault_request_withdrawal',
  'staking_vault_claim_withdrawal',
  'staking_vault_process_epoch',
  'staking_vault_add_operator',
  'staking_vault_update_operator_allocations',
  'staking_vault_initiate_validator_registration',
  'staking_vault_complete_validator_registration',
  'staking_vault_initiate_validator_removal',
  'staking_vault_complete_validator_removal',
  'staking_vault_initiate_delegator_registration',
  'staking_vault_complete_delegator_registration',
  'staking_vault_initiate_delegator_removal',
  'staking_vault_complete_delegator_removal',
  'balancer_set_up_security_module',
  'balancer_resend_validator_registration',
  'balancer_resend_weight_update',
  'balancer_resend_validator_removal',
  'balancer_transfer_l1_ownership',
  'poa_add_node',
  'poa_complete_validator_registration',
  'poa_remove_node',
  'poa_complete_validator_removal',
  'poa_init_weight_update',
  'poa_complete_weight_update',
  'rewards_set_amount',
  'rewards_claim_undistributed',
  'lst_wrapper_deposit',
  'lst_wrapper_redeem',
  'lst_wrapper_harvest',
  'uptime_report_validator',
  'uptime_compute_operator_uptime',
] as const;

function sorted(values: readonly string[]): string[] {
  return [...values].sort();
}

export const EXPECTED_PROFILE_TOOL_NAMES = {
  full: sorted([...READ_ONLY_TOOL_NAMES, ...FULL_WRITE_TOOL_NAMES]),
  readOnly: sorted(READ_ONLY_TOOL_NAMES),
} as const;
