name: development

on:
  workflow_dispatch:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: pnpm install --frozen-lockfile # the install command trigger the build through the prepare script
      - run: pnpx esbuild --bundle --platform=node --target=node22 --external:usb --external:@ledgerhq/hw-transport-node-hid --outfile=suzaku-cli.js ./src/cli.ts

      - name: test
        run: ./suzaku-cli.js --help

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: cli-dist
          path: |
            suzaku-cli.js
