name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: pnpm install --frozen-lockfile # the install command trigger the build through the prepare script
      - run: pnpm --filter @suzaku-network/mcp build

      - name: test
        run: pnpm suzaku-cli --help

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: false
          make_latest: true
